/**
 * Generate RLS policy rewrites to wrap auth.* calls in subselect
 * 
 * This script queries pg_policies for policies with unwrapped auth.uid(), auth.jwt(), auth.role()
 * and generates CREATE OR REPLACE POLICY statements with the (select auth.fn()) pattern.
 * 
 * Usage: npx tsx scripts/generate-auth-rls-wrap.ts
 */

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.VITE_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('VITE_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

interface Policy {
  schemaname: string;
  tablename: string;
  policyname: string;
  qual: string | null;
  with_check: string | null;
}

function wrapAuthFunctions(expression: string | null): string {
  if (!expression) return '';
  
  // Wrap auth.uid(), auth.jwt(), auth.role() in (select ...)
  // Pattern: auth.uid() → (select auth.uid())
  // Pattern: auth.jwt() → (select auth.jwt())
  // Pattern: auth.role() → (select auth.role())
  
  let wrapped = expression;
  
  // Replace auth.uid() with (select auth.uid())
  wrapped = wrapped.replace(/\bauth\.uid\(\)/g, '(select auth.uid())');
  
  // Replace auth.jwt() with (select auth.jwt())
  wrapped = wrapped.replace(/\bauth\.jwt\(\)/g, '(select auth.jwt())');
  
  // Replace auth.role() with (select auth.role())
  wrapped = wrapped.replace(/\bauth\.role\(\)/g, '(select auth.role())');
  
  return wrapped;
}

function generatePolicySQL(policy: Policy): string {
  const { schemaname, tablename, policyname, qual, with_check } = policy;
  
  const wrappedQual = wrapAuthFunctions(qual);
  const wrappedWithCheck = wrapAuthFunctions(with_check);
  
  let sql = `CREATE OR REPLACE POLICY "${policyname}" ON "${schemaname}"."${tablename}"\n`;
  
  // Determine command from policy name patterns
  let command = 'ALL';
  if (policyname.includes('_select_')) command = 'SELECT';
  else if (policyname.includes('_insert_')) command = 'INSERT';
  else if (policyname.includes('_update_')) command = 'UPDATE';
  else if (policyname.includes('_delete_')) command = 'DELETE';
  
  sql += `  FOR ${command}\n`;
  sql += `  TO authenticated\n`;
  
  if (wrappedQual) {
    sql += `  USING (${wrappedQual})\n`;
  }
  
  if (wrappedWithCheck) {
    sql += `  WITH CHECK (${wrappedWithCheck})\n`;
  }
  
  sql += ';\n';
  
  return sql;
}

async function main() {
  console.log('Querying pg_policies for unwrapped auth.* calls...');
  
  // Use direct SQL query to find policies with unwrapped auth.* calls
  const { data: policiesData, error: queryError } = await supabase
    .from('pg_policies')
    .select('schemaname, tablename, policyname, qual, with_check')
    .or('qual~*auth\\.(uid|jwt|role)\\(\\),with_check~*auth\\.(uid|jwt|role)\\(\\)')
    .order('schemaname, tablename, policyname');
  
  if (queryError) {
    console.error('Error querying pg_policies:', queryError);
    process.exit(1);
  }
  
  const policiesTyped = policiesData as Policy[];
  
  console.log(`Found ${policiesTyped.length} policies with unwrapped auth.* calls\n`);
  
  // Generate migration file
  let migration = '-- Migration: Wrap auth.* calls in RLS policies for performance\n';
  migration += '-- Generated by scripts/generate-auth-rls-wrap.ts\n';
  migration += '-- IPI-854 (SB-PERF-003) — Optimize auth_rls_initplan Performance\n';
  migration += '-- This wraps auth.uid(), auth.jwt(), auth.role() in (select ...)\n';
  migration += '-- to evaluate once per statement instead of once per row\n';
  migration += '-- Reference: https://supabase.com/docs/guides/database/database-advisors\n\n';
  
  policiesTyped.forEach((policy, index) => {
    migration += `-- Policy ${index + 1}/${policiesTyped.length}: ${policy.schemaname}.${policy.tablename}.${policy.policyname}\n`;
    migration += generatePolicySQL(policy);
    migration += '\n';
  });
  
  console.log('Generated migration:\n');
  console.log(migration);
  
  // Write to file in tasks/audit/supabase/migrations
  const fs = await import('fs');
  const path = await import('path');
  
  const migrationDir = path.join(process.cwd(), 'tasks', 'audit', 'supabase', 'migrations');
  if (!fs.existsSync(migrationDir)) {
    fs.mkdirSync(migrationDir, { recursive: true });
  }
  
  const migrationPath = path.join(migrationDir, `20260730_wrap_auth_rls_initplan.sql`);
  fs.writeFileSync(migrationPath, migration);
  
  console.log(`\nMigration written to: ${migrationPath}`);
  console.log(`\nNext steps:`);
  console.log(`1. Review the generated migration`);
  console.log(`2. Apply via: cd tasks/audit/supabase && supabase db push`);
  console.log(`3. Verify with: supabase db advisors`);
  console.log(`4. Run RLS verification: npm run test:rls`);
}

main().catch(console.error);
