/**
 * Generate migration to consolidate multiple permissive RLS policies
 * IPI-861 (SB-PERF-004) — Consolidate Multiple Permissive RLS Policies
 * 
 * This script queries pg_policies for groups of multiple permissive policies
 * on the same table/role/command and generates ALTER POLICY + DROP POLICY statements
 * to consolidate them into single policies with OR expressions.
 * 
 * Usage: npx tsx scripts/generate-consolidate-permissive-policies.ts
 */

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.VITE_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('VITE_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

interface PolicyGroup {
  schemaname: string;
  tablename: string;
  cmd: string;
  roles: string[];
  policy_count: number;
  policies: Policy[];
}

interface Policy {
  policyname: string;
  qual: string | null;
  with_check: string | null;
}

async function main() {
  console.log('Querying pg_policies for multiple permissive policies...\n');

  // Query to group policies by table/role/command
  const { data: groups, error: groupError } = await supabase.rpc('get_multiple_permissive_policy_groups', {
    // We'll use a direct SQL query instead
  });

  // Use direct SQL query
  const { data: policyGroups, error: queryError } = await supabase
    .from('pg_policies')
    .select('schemaname, tablename, cmd, roles, policyname, qual, with_check')
    .eq('permissive', 'PERMISSIVE')
    .order('schemaname, tablename, cmd, policyname');

  if (queryError) {
    console.error('Error querying pg_policies:', queryError);
    process.exit(1);
  }

  // Group policies by table/role/command
  const groupMap = new Map<string, PolicyGroup>();

  policyGroups?.forEach((policy: any) => {
    const key = `${policy.schemaname}.${policy.tablename}|${policy.cmd}|${policy.roles}`;
    
    if (!groupMap.has(key)) {
      groupMap.set(key, {
        schemaname: policy.schemaname,
        tablename: policy.tablename,
        cmd: policy.cmd,
        roles: Array.isArray(policy.roles) ? policy.roles : [policy.roles],
        policy_count: 0,
        policies: []
      });
    }
    
    const group = groupMap.get(key)!;
    group.policy_count++;
    group.policies.push({
      policyname: policy.policyname,
      qual: policy.qual,
      with_check: policy.with_check
    });
  });

  // Filter to groups with multiple policies
  const multiPolicyGroups = Array.from(groupMap.values()).filter(g => g.policy_count > 1);
  
  console.log(`Found ${multiPolicyGroups.length} groups with multiple permissive policies\n`);

  if (multiPolicyGroups.length === 0) {
    console.log('No multiple permissive policies found. Nothing to do.');
    return;
  }

  // Generate migration
  let migration = '-- Migration: Consolidate multiple permissive RLS policies\n';
  migration += '-- Generated by scripts/generate-consolidate-permissive-policies.ts\n';
  migration += '-- IPI-861 (SB-PERF-004) — Consolidate Multiple Permissive RLS Policies\n';
  migration += '-- This consolidates multiple permissive policies into single policies with OR expressions\n';
  migration += '-- Postgres combines permissive policies with OR, so this is semantically equivalent\n';
  migration += '-- Reference: https://supabase.com/docs/guides/database/database-linter?lint=0006_multiple_permissive_policies\n\n';

  multiPolicyGroups.forEach((group, groupIndex) => {
    migration += `-- Group ${groupIndex + 1}/${multiPolicyGroups.length}: ${group.schemaname}.${group.tablename} (${group.cmd})\n`;
    migration += `-- ${group.policy_count} policies: ${group.policies.map(p => p.policyname).join(', ')}\n\n`;

    // Keep the first policy, widen it, drop the rest
    const survivor = group.policies[0];
    const toDrop = group.policies.slice(1);

    // Build OR expressions
    const qualOr = group.policies
      .map(p => p.qual)
      .filter(q => q !== null)
      .join(' OR ');
    
    const withCheckOr = group.policies
      .map(p => p.with_check)
      .filter(w => w !== null)
      .join(' OR ');

    // ALTER POLICY to widen the survivor
    if (qualOr) {
      migration += `ALTER POLICY ${survivor.policyname} ON ${group.schemaname}.${group.tablename}\n`;
      migration += `  USING (${qualOr});\n`;
    }
    
    if (withCheckOr) {
      migration += `ALTER POLICY ${survivor.policyname} ON ${group.schemaname}.${group.tablename}\n`;
      migration += `  WITH CHECK (${withCheckOr});\n`;
    }

    if (qualOr || withCheckOr) {
      migration += '\n';
    }

    // DROP POLICY for the redundant siblings
    toDrop.forEach(policy => {
      migration += `DROP POLICY IF EXISTS ${policy.policyname} ON ${group.schemaname}.${group.tablename};\n`;
    });

    migration += '\n';
  });

  console.log('Generated migration:\n');
  console.log(migration);

  // Write to file
  const fs = await import('fs');
  const path = await import('path');

  const migrationDir = path.join(process.cwd(), 'tasks', 'audit', 'supabase', 'migrations');
  if (!fs.existsSync(migrationDir)) {
    fs.mkdirSync(migrationDir, { recursive: true });
  }

  const migrationPath = path.join(migrationDir, '20260730_consolidate_multiple_permissive_policies.sql');
  fs.writeFileSync(migrationPath, migration);

  console.log(`\nMigration written to: ${migrationPath}`);
  console.log(`\nNext steps:`);
  console.log(`1. Review the generated migration`);
  console.log(`2. Apply via: cd tasks/audit/supabase && supabase db push`);
  console.log(`3. Verify with: supabase db advisors`);
  console.log(`4. Run RLS verification: npm run test:rls`);
  console.log(`\nExpected: multiple_permissive_policies count drops from 35 to 0`);
}

main().catch(console.error);
