-- Migration: Wrap auth.* calls in RLS policies for performance
-- Generated by scripts/generate-auth-rls-wrap.ts
-- IPI-854 (SB-PERF-003) — Optimize auth_rls_initplan Performance
-- This wraps auth.uid(), auth.jwt(), auth.role() in (select ...)
-- to evaluate once per statement instead of once per row
-- Reference: https://supabase.com/docs/guides/database/database-advisors

-- Note: This migration will be generated by running:
-- npx tsx scripts/generate-auth-rls-wrap.ts
-- which queries pg_policies for all policies with unwrapped auth.* calls
-- and generates CREATE OR REPLACE POLICY statements.

-- Expected: 145 policies to be rewritten
-- Status: 91 of 236 auth.*-referencing policies already wrapped (39% done)

-- After applying this migration, verify with:
-- supabase db advisors
-- npm run test:rls
