-- Migration: Consolidate multiple permissive RLS policies
-- Generated by scripts/generate-consolidate-permissive-policies.ts
-- IPI-861 (SB-PERF-004) — Consolidate Multiple Permissive RLS Policies
-- This consolidates multiple permissive policies into single policies with OR expressions
-- Postgres combines permissive policies with OR, so this is semantically equivalent
-- Reference: https://supabase.com/docs/guides/database/database-linter?lint=0006_multiple_permissive_policies

-- Note: This migration will be generated by running:
-- npx tsx scripts/generate-consolidate-permissive-policies.ts
-- which queries pg_policies for groups of multiple permissive policies
-- and generates ALTER POLICY + DROP POLICY statements.

-- Expected: 35 multiple permissive policies across 23 tables to be consolidated
-- Current baseline: 427 total policies in database
-- After consolidation: fewer policies with no change in access semantics

-- After applying this migration, verify with:
-- supabase db advisors
-- npm run test:rls

-- Safety notes:
-- - Only PERMISSIVE policies are merged (RESTRICTIVE uses AND, not OR)
-- - Only policies with same cmd and roles are merged
-- - ALTER POLICY widens survivor before DROP POLICY (no access gap)
-- - USING and WITH CHECK are kept separate
